# Generated by Django 3.2.9 on 2021-12-14 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('nombre_editorial', models.CharField(max_length=50)),
                ('cantidad_paginas', models.PositiveIntegerField()),
                ('fecha_publicacion', models.DateField()),
                ('isbn', models.CharField(max_length=17)),
                ('archivo_libro', models.FileField(upload_to='libros')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='libreria.autor')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('opinion', models.TextField()),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='usuario_imagenes')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('reviews', models.ManyToManyField(through='libreria.Review', to='libreria.Libro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.usuario'),
        ),
        migrations.AddField(
            model_name='autor',
            name='usuarios_suscritos',
            field=models.ManyToManyField(blank=True, related_name='autores_suscritos', to='libreria.Usuario'),
        ),
    ]
