# Generated by Django 3.2.9 on 2021-12-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='fucha_nacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
