# Generated by Django 3.2.9 on 2021-12-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='opinion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
